### ISSUE TITLE
Examples dont start

### ISSUE THREAD

**Issue by pke** [nsmith7989/redux-filter#21]
There seem to be several problems with the examples:

> Warning: you are using an outdated format of React Transform configuration. Please update your configuration to the new format. See the Releases page for migraorm/releases

and

>   [236](webpack)-hot-middleware/process-update.js 2.94 kB {0} [built]
>   [237](webpack)-hot-middleware/client.js?reload=true 3.24 kB {0} [built]
> ERROR in ./~/redbox-react/lib/index.js
> Module build failed: ReferenceError: Unknown plugin "rewire"
>     at PluginManager.subnormaliseString (C:\dev\projects\redux-filter\examples\product-filtering\node_modules\babel-core\lib\transformation\file\plugin-manager
>     at PluginManager.add (C:\dev\projects\redux-filter\examples\product-filtering\node_modules\babel-core\lib\transformation\file\plugin-manager.js:190:40)
>     at File.buildTransformers (C:\dev\projects\redux-filter\examples\product-filtering\node_modules\babel-core\lib\transformation\file\index.js:237:21)
>     at new File (C:\dev\projects\redux-filter\examples\product-filtering\node_modules\babel-core\lib\transformation\file\index.js:139:10)
>     at Pipeline.transform (C:\dev\projects\redux-filter\examples\product-filtering\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
>     at transpile (C:\dev\projects\redux-filter\examples\product-filtering\node_modules\babel-loader\index.js:12:22)
>     at Object.module.exports (C:\dev\projects\redux-filter\examples\product-filtering\node_modules\babel-loader\index.js:71:12)
>  @ ./index.js 13:19-42

**Comment by nsmith7989** [comment]
1) Is just a warning from the babel plugin. I'll change the `.babelrc` with the updated configuration. 
2) Appears to be specific to Redbox React: https://github.com/KeywordBrain/redbox-react/issues/34, but it seems to be fixed if I add `babel-plugin-rewire` to devDependencies. 

Please reopen if this does not fix your issue.

**Comment by pke** [comment]
Works now! Thanks
