### ISSUE TITLE
Integration Example Broken

### ISSUE THREAD

**Issue by jeffcatania** [nsmith7989/redux-filter#23]
This looks like a very promising component.  However, I am having trouble integrating with an existing redux app that I am building.

From a fresh install of the integration example, I am getting the following error in my browser console:

```
Uncaught TypeError: (0 , _reduxFilter.buildInitialState) is not a function
```

It seems that there is some restructuring that is being done with how the buildInitialState gets invoked with regards to the subjects being passed into it.  Any pointers would be very helpful.

**Comment by nsmith7989** [comment]
You're right, it's a bit of a mess. 

I'm working on cleaning it up. After I get my tests fixed it should look something like this: https://github.com/nsmith7989/redux-filter/blob/selector-options/examples/integration/index.js

I appreciate you bringing this to my attention.

**Comment by nsmith7989** [comment]
I think the integration is much simpler now. https://github.com/nsmith7989/redux-filter/blob/master/examples/integration/index.js
