### ISSUE TITLE
T-shirt example broken since v2.0.0

### ISSUE THREAD

**Issue by barrystaes** [nsmith7989/redux-filter#25]
I wanted to take a first look at `redux-filter` but the [t-shirt demo](https://github.com/nsmith7989/redux-filter/tree/b199d9bcbf8b940ca80df5ddcb378392093c77bb/examples/product-filtering) seems to have a problem.

I then tried the Latest and v2.1.0 and discovered that it the page stays empty, and the console contains this error:

```
APPLY_SORT
dispatching Objectfunc: Objecttype: "APPLY_SORT"__proto__: Object
Uncaught TypeError: Cannot read property 'appliedFilters' of undefined
[HMR] connected
```

But when i checkout the older v2.0.0 example it all works as it should.

**Comment by nsmith7989** [comment]
Looks like the example had a hard coded version of the library. Fixed in PR #27
