### ISSUE TITLE
Examples have the issue "react-transform-catch-errors does not look like a React component"

### ISSUE THREAD

**Issue by Saajan** [nsmith7989/redux-filter#29]
First of all thanks for the filters for redux , i love them . But when i try to install the examples in my system it didnt work . it was giving the error "react-transform-catch-errors does not look like a React component" when i ran "npm start".
Anyway i found out the solution for the issue.It is with the "redbox-react": "^1.0.6" " . Just remove "^" for the dependency such that it downloads the exact version of redbox-react. I guess the newer version of the library has the bug.

**Comment by nsmith7989** [comment]
Thanks for the catch. You're absolutely right.
